//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carcas
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionsCategory
    {
        public int Id_QuestionsCategory { get; set; }
        public Nullable<int> Id_Category_FK_ { get; set; }
        public Nullable<int> Id_Questions_FK_ { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
